export const allProducts = [
    {
        id: 1,
        type: 'gift',
        line: '',
        badge: 'new',
        name: '설화수 베스트셀러 컬렉션',
        nameEn: 'Sulhwasoo Bestsellers',
        price: '295,000',
        size: ' ',
        image: './images/product/sulwhasoo-bestsellers-set_thumb_640_01_kr_230313.jpg'
    },
    {
        id: 2,
        type: 'gift',
        line: '',
        badge: 'new',
        name: '나의 첫 설화수 세트',
        nameEn: 'My first Sulwhasoo Set',
        price: '140,000',
        size: ' ',
        image: './images/product/20230227_final_My-first-Sulhwasoo_thumb_640.jpg'
    },
    {
        id: 3,
        type: 'boostessence',
        line: 'yunjo',
        badge: 'new',
        name: '윤조에센스 6세대',
        nameEn: 'First Care Activating Serum Ⅵ',
        price: '55,000',
        size: '3size',
        image: './images/product/First-Care-Activating-Serum-VI-90ml_Thumb_2.jpg'
    },
    {
        id: 4,
        type: 'skin',
        line: 'yunjoperfecting',
        badge: 'exclusive',
        name: '윤조수 퍼펙팅',
        nameEn: 'First Care Activating Perfecting Water',
        price: '78,000',
        size: '150ml',
        image: './images/product/First-Care-Activating-Perfecting-Water-150ml.jpg'
    },
    {
        id: 5,
        type: 'lotion',
        line: 'yunjoperfecting',
        badge: 'exclusive',
        name: '윤조유액 퍼펙팅',
        nameEn: 'First Care Activating Perfecting Emulsion',
        price: '82,000',
        size: '125ml',
        image: './images/product/First-Care-Activating-Perfecting-Emulsion-125ml.jpg'
    },
    {
        id: 6,
        type: 'eyecream',
        line: 'yunjoperfecting',
        badge: 'exclusive',
        name: '윤조아이크림 퍼펙팅',
        nameEn: 'First Care Activating Perfecting Eye Cream',
        price: '100,000',
        size: '20ml',
        image: './images/product/First-Care-Activating-Perfecting-Eye-Cream-20ml.jpg'
    },
    {
        id: 7,
        type: 'essence_ample',
        line: 'jaumbright',
        badge: '',
        name: '자음생앰플 브라이트닝',
        nameEn: 'Concentrated Ginseng Brightening Spot Ampoule',
        price: '140,000',
        size: '20g',
        image: './images/product/CGR-Brightening-Serum-Ampoule-20g_Thumb.jpg'
    },
    {
        id: 8,
        type: 'essence_ample',
        line: 'jaumbright',
        badge: '',
        name: '자음생세럼 브라이트닝',
        nameEn: 'Concentrated Ginseng Brightening Serum',
        price: '145,000',
        size: '2size',
        image: './images/product/CGR-Brightening-Serum-50ml_Thumb.jpg'
    },
    {
        id: 9,
        type: 'cream',
        line: 'jaum',
        badge: 'exclusive',
        name: '자음생크림 퍼펙팅 클래식',
        nameEn: 'Concentrated Ginseng Renewing Perfecting Cream EX Classic',
        price: '270,000',
        size: '60ml',
        image: './images/product/Concentrated-Ginseng-Renewing-Perfecting-Cream-EX-Classic-60ml.jpg'
    },
    {
        id: 10,
        type: 'mask',
        line: 'yunjo',
        badge: 'new',
        name: '윤조마스크EX',
        nameEn: 'First Care Activating Mask EX',
        price: '60,000',
        size: '5매(23g/매)',
        image: './images/product/First-Care-Activating-Mask-EX-1ea_Thumb.jpg'
    },
    {
        id: 11,
        type: 'essence_ample',
        line: 'jaum',
        badge: 'new',
        name: '자음생세럼',
        nameEn: 'Concentrated Ginseng Renewing Serum EX',
        price: '145,000',
        size: '2size',
        image: './images/product/CGR-Serum-EX-50ml_Thumb.jpg'
    },
    {
        id: 12,
        type: 'eyecream',
        line: 'jaum',
        badge: '',
        name: '자음생아이크림',
        nameEn: 'Concentrated Ginseng Renewing Eye Cream',
        price: '160,000',
        size: '20ml',
        image: './images/product/CGR-Eye-Cream-20ml_Thumb.jpg'
    },
    {
        id: 13,
        type: 'mask',
        line: '',
        badge: 'new',
        name: '자음생마스크EX',
        nameEn: 'Concentrated Ginseng Renewing Creamy Mask EX',
        price: '125,000',
        size: '5매',
        image: './images/product/CGR-Creamy-Mask-EX-1ea_Thumb.jpg'
    },
    {
        id: 14,
        type: 'cream',
        line: 'perfect',
        badge: 'exclusive',
        name: '수분영양크림',
        nameEn: 'Essential Perfecting Intensive Moisturizing Cream',
        price: '80,000',
        size: '50ml',
        image: './images/product/Essential-Perfecting-Intensive-Moisturizing-Cream-50ml.jpg'
    },
    {
        id: 15,
        type: 'cream',
        line: 'perfect',
        badge: 'exclusive',
        name: '탄력영양크림',
        nameEn: 'Essential Perfecting Intensive Firming Cream',
        price: '120,000',
        size: '75ml',
        image: './images/product/Essential-Perfecting-Intensive-Firming-Cream-75ml.jpg'
    },
    {
        id: 16,
        type: 'skin',
        line: 'perfect',
        badge: 'exclusive',
        name: '자음수 퍼펙팅',
        nameEn: 'Essential Perfecting Balancing Water',
        price: '68,000',
        size: '150ml',
        image: './images/product/Essential-Perfecting-Balancing-Water-150ml.jpg'
    },
    {
        id: 17,
        type: 'lotion',
        line: 'perfect',
        badge: 'exclusive',
        name: '자음유액 퍼펙팅',
        nameEn: 'Essential Perfecting Balancing Emulsion',
        price: '72,000',
        size: '125ml',
        image: './images/product/Essential-Perfecting-Balancing-Emulsion-125ml.jpg'
    },
    {
        id: 18,
        type: 'skin',
        line: 'comfort',
        badge: 'BEST',
        name: '자음수',
        nameEn: 'Essential Comfort Balancing Water',
        price: '68,000',
        size: '150ml',
        image: './images/product/230228_final_Essential-Comfort-Balancing-Water-150ml_thumbnail(640x640)_1.jpg'
    },
    {
        id: 19,
        type: 'lotion',
        line: 'comfort',
        badge: 'BEST',
        name: '자음유액',
        nameEn: 'Essential Comfort Balancing Emulsion',
        price: '72,000',
        size: '125ml',
        image: './images/product/230228_final_Essential-Comfort-Balancing-Emulsion-125ml_thumbnail(640x640)_1.jpg'
    },
    {
        id: 20,
        type: 'cream',
        line: 'comfort',
        badge: '',
        name: '탄력크림',
        nameEn: 'Essential Comfort Firming Cream',
        price: '90,000',
        size: '2size',
        image: './images/product/230228_final_Essential-Comfort-Firming-Cream-75ml_thumbnail(640x640)_2.jpg'
    },
    {
        id: 21,
        type: 'cream',
        line: 'jaum',
        badge: 'BEST',
        name: '자음생크림',
        nameEn: 'Concentrated Ginseng Renewing Cream EX',
        price: '150,000',
        size: '2size',
        image: './images/product/Concentrated-Ginseng-Renewing-Perfecting-Cream-EX-Classic-60ml.jpg'
    },
    {
        id: 22,
        type: 'boostessence',
        line: 'yunjoperfecting',
        badge: 'exclusive',
        name: '윤조에센스 퍼펙팅',
        nameEn: 'First Care Activating Perfecting Serum',
        price: '140,000',
        size: '2size',
        image: './images/product/First-Care-Activating-Perfecting-Serum-90ml.jpg'
    },
    {
        id: 23,
        type: 'essence_ample',
        line: 'jaum',
        badge: '',
        name: '자음생앰플',
        nameEn: 'Concentrated Ginseng Rescue Ampoule',
        price: '140,000',
        size: '20g',
        image: './images/product/CGR-Ampoule-20g.jpg'
    },
    {
        id: 24,
        type: 'skin',
        line: 'jaum',
        badge: '',
        name: '자음생수EX',
        nameEn: 'Concentrated Ginseng Renewing Water EX',
        price: '100,000',
        size: '150ml',
        image: './images/product/CGR-Water-EX-150ml_Thumb.jpg'
    },
    {
        id: 25,
        type: 'lotion',
        line: 'jaum',
        badge: '',
        name: '자음생유액EX',
        nameEn: 'Concentrated Ginseng Renewing Emulsion EX',
        price: '105,000',
        size: '125ml',
        image: './images/product/CGR-Emulsion-EX-125ml_Thumb.jpg'
    },
    {
        id: 26,
        type: 'sunblock',
        line: 'etc',
        badge: 'BEST',
        name: '상백크림',
        nameEn: 'UV Wise Brightening Multi Protector',
        price: '85,000',
        size: '50ml',
        image: './images/product/UV-Wise-Brightening-Multi-Protector-50ml_Thumb_1.jpg'
    },
    {
        id: 27,
        type: 'mask',
        line: 'etc',
        badge: '',
        name: '백삼팩',
        nameEn: 'White Ginseng Radiance Refining Mask',
        price: '72,000',
        size: '120ml',
        image: './images/product/230228_final_White-Ginseng-Refining-Radiance-Mask-120ml_thumbnail(640x640)_1.jpg'
    },
    {
        id: 28,
        type: 'mask',
        line: 'etc',
        badge: '',
        name: '옥용팩',
        nameEn: 'Clarifying Mask',
        price: '53,000',
        size: '120ml',
        image: './images/product/230228_final_Clarifying-Mask-120ml_thumbnail(640x640)_1.jpg'
    },
    {
        id: 29,
        type: 'mask',
        line: 'etc',
        badge: '',
        name: '여윤팩',
        nameEn: 'Overnight Vitalizing Mask',
        price: '65,000',
        size: '120ml',
        image: './images/product/230228_final_Overnight-Vitalizing-Mask-120ml_thumbnail(640x640)_1.jpg'
    },
    {
        id: 30,
        type: 'essence_ample',
        line: 'jinseol',
        badge: '',
        name: '진설에센스',
        nameEn: 'Timetreasure Invigorating Serum',
        price: '380,000',
        size: '50ml',
        image: './images/product/Timetreasure-Invigorating-Serum-50ml_Thumb.jpg'
    },
    {
        id: 31,
        type: 'cream',
        line: 'jinseol',
        badge: '',
        name: '진설크림',
        nameEn: 'Timetreasure Invigorating Cream',
        price: '470,000',
        size: '60ml',
        image: './images/product/Timetreasure-Invigorating-Cream-60ml_Thumb.jpg'
    },
    {
        id: 32,
        type: 'eyecream',
        line: 'jinseol',
        badge: '',
        name: '진설아이에센스',
        nameEn: 'Timetreasure Invigorating Eye Serum',
        price: '270,000',
        size: '25ml',
        image: './images/product/Timetreasure-Invigorating-Eye-Serum-25ml_Thumb.jpg'
    },
    {
        id: 33,
        type: 'eyecream',
        line: 'jinseol',
        badge: 'BEST',
        name: '진설아이크림',
        nameEn: 'Timetreasure Invigorating Eye Cream',
        price: '270,000',
        size: '25ml',
        image: './images/product/Timetreasure-Invigorating-Eye-Cream-25ml_Thumb.jpg'
    },
    {
        id: 34,
        type: 'skin',
        line: 'jinseol',
        badge: '',
        name: '진설수',
        nameEn: 'Timetreasure Invigorating Water EX',
        price: '125,000',
        size: '125ml',
        image: './images/product/Timetreasure-Invigorating-Water-125ml_Thumb.jpg'
    },
    {
        id: 35,
        type: 'lotion',
        line: 'jinseol',
        badge: '',
        name: '진설유액',
        nameEn: 'Timetreasure Invigorating Emulsion EX',
        price: '140,000',
        size: '125ml',
        image: './images/product/Timetreasure-Invigorating-Emulsion-125ml_Thumb.jpg'
    },
    {
        id: 36,
        type: 'mask',
        line: 'jinseol',
        badge: '',
        name: '진설마스크',
        nameEn: 'Timetreasure Invigorating Sleeping Mask',
        price: '200,000',
        size: '80ml',
        image: './images/product/Timetreasure-Invigorating-Sleeping-Mask-80ml_Thumb.jpg'
    },
    {
        id: 37,
        type: 'cleansing',
        line: 'jinseol',
        badge: '',
        name: '진설클렌징폼',
        nameEn: 'Timetreasure Extra Creamy Cleansing Foam',
        price: '60,000',
        size: '150ml',
        image: './images/product/Timetreasure-Extra-Creamy-Cleansing-Foam-150ml_Thumb.jpg'
    },
    {
        id: 38,
        type: 'cleansing',
        line: 'etc',
        badge: '',
        name: '순행클렌징오일',
        nameEn: 'Gentle Cleansing Oil',
        price: '47,000',
        size: '2size',
        image: './images/product/230531_Gentle-Cleansing-Oil-400ml_thumb_640.jpg'
    },
    {
        id: 39,
        type: 'cleansing',
        line: 'etc',
        badge: 'BEST',
        name: '순행클렌징폼',
        nameEn: 'Gentle Cleansing Foam',
        price: '42,000',
        size: '2size',
        image: './images/product/230531_Gentle-Cleansing-Foam-400ml_thumb_640.jpg'
    },
    {
        id: 40,
        type: 'cleansing',
        line: 'etc',
        badge: '',
        name: '궁중비누',
        nameEn: 'Herbal Soap',
        price: '45,000',
        size: '100g*2 , 비누받침대',
        image: './images/product/210517_final_KR_HerbalSoap_1.jpg'
    },
    {
        id: 41,
        type: 'essence_ample',
        line: 'jjin',
        badge: '',
        name: '진설명작에센스',
        nameEn: 'Timetreasure Honorstige Serum',
        price: '800,000',
        size: '40ml',
        image: './images/product/Timetreasure-Honorstige-Serum-40ml.jpg'
    },
    {
        id: 42,
        type: 'cream',
        line: 'jjin',
        badge: '',
        name: '진설명작크림',
        nameEn: 'Timetreasure Honorstige Cream',
        price: '800,000',
        size: '60ml',
        image: './images/product/Timetreasure-Honorstige-Cream-60ml.jpg'
    },
];
